# Generated by Django 2.2.3 on 2019-07-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField()),
                ('system', models.CharField(choices=[('U', '大學院校'), ('T', '大專院校')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('graduate', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.University')),
            ],
        ),
    ]
