# Generated by Django 2.2.3 on 2019-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='system',
            field=models.CharField(max_length=200),
        ),
    ]
