# Generated by Django 2.2.3 on 2019-07-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190722_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='schools.University'),
        ),
    ]
