# Generated by Django 2.2.3 on 2019-07-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190722_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='building_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='campus_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
