# Generated by Django 2.2.3 on 2019-07-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_university_edu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='F_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='M_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
