# Generated by Django 2.2.3 on 2019-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190723_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='money',
            new_name='funding',
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='project_funding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='register_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='teachers',
            field=models.IntegerField(default=0),
        ),
    ]
